# Generated by Django 3.0.3 on 2020-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
