# Generated by Django 3.0.4 on 2020-03-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='Category',
        ),
    ]
