# Generated by Django 3.0.3 on 2020-03-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition_grade',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fat in 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritionGrade',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Salt in 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='satFat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Saturated fat in 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Sugar in 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('codeHealthy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthy', to='products.Product')),
                ('codeUnhealthy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unhealthy', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
