# Generated by Django 3.0.3 on 2020-03-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200319_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategories',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='compared_to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategories'),
        ),
    ]
