# Generated by Django 3.0.4 on 2020-05-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200421_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='codeHealthy',
            new_name='healthy_product',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='codeUnhealthy',
            new_name='unhealthy_product',
        ),
    ]
