# Generated by Django 3.0.4 on 2020-03-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200323_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(related_name='categories', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compared_to_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_to_category', to='products.Category'),
        ),
    ]
