# Generated by Django 3.0.4 on 2020-05-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200501_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__id'], 'verbose_name': 'Produit'},
        ),
    ]
