# Generated by Django 3.0.4 on 2020-04-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200329_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compared_to_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.Category'),
        ),
    ]
