# Generated by Django 3.0.4 on 2020-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200508_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritionGrade',
            field=models.CharField(max_length=1, null=True, verbose_name='Nutriscore'),
        ),
    ]
